# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: docker build -t idjohnson/node-demo .
  displayName: 'Docker Build'

- script: |
    echo $(docker-pass) | docker login -u $(docker-username) --password-stdin
    echo now tag
    docker tag idjohnson/node-demo idjohnson/idjdemo:$(Build.BuildId)
    docker tag idjohnson/node-demo idjohnson/idjdemo:$(Build.SourceVersion)
    docker tag idjohnson/node-demo idjohnson/idjdemo:latest
    docker push idjohnson/idjdemo
  displayName: 'Run a multi-line script'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*.yaml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
    CleanTargetFolder: true
    OverWrite: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
